config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :pins, :boards

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_and_belongs_to_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  has_and_belongs_to_many :boards
  validates :title, presence: true, length: { minimum: 1 }
  validates :image_url, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render 'new'
    end
  end

  def show
    @board = Board.find(params[:id])
    @pins = @board.pins
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path
    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private
    def board_params
      params.require(:board).permit(:title)
    end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  def index
    @pins = Pin.all
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to pins_path
    else
      render 'new'
    end
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def edit
    @pin = Pin.find(params[:id])
    @boards = Board.all
  end

  def update
    @pin = Pin.find(params[:id])
    if @pin.update(pin_params)
      redirect_to pins_path
    else
      render 'edit'
    end
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    redirect_to pins_path
  end

  private
    def pin_params
      params.require(:pin).permit(:title, :image_url)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/_board.html.haml
.board
  %h3= link_to board.title, board
  %ul.options
    %li= link_to 'edit', edit_board_path(board)
    %li= link_to 'destroy', board_path(board), method: :delete, data: { confirm: 'Are you sure?' }

app/views/boards/_form.html.erb
<%= form_for [@user, @board] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h4
        = pluralize @board.errors.count, 'error'
        prohibited this board from being saved
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg
  .board_form
    = f.label :title
    = f.text_field :title
    = f.submit

app/views/boards/edit.html.erb
<h2>Edit Board</h2>

<%= render 'form' %>

<%= link_to 'Delete Board', user_board_path(@user, @board), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/boards/edit.html.haml
%h2 Rename Board?
= render 'form'

app/views/boards/index.html.erb
<div id="board-container">
  <% @boards.each do |board| %>
    <div class="board">
      <div class="board-photo"></div>
      <%= link_to board.title, user_board_path(@user, board), class: "board-title" %>
    </div>
  <% end %>
</div>

app/views/boards/index.html.haml
%h2 Boards#index
= render @boards

app/views/boards/new.html.erb
<h2>New Board</h2>

<%= render 'form' %>

app/views/boards/new.html.haml
%h2 New Board?
= render 'form'

app/views/boards/show.html.erb
<%= link_to "New Pin", new_user_board_pin_path(@user, @board), id: "new-pin" %>

<div id="board-container">
  <% @board.pins.each do |pin| %>
    <div class="board">
      <%= link_to image_tag( pin.image_url ), pin_path(pin) %>
      <%= link_to pin.title, pin_path(pin), class: "board-title" %>
    </div>
  <% end %>
</div>

<%= link_to "Edit Board", edit_user_board_path(@user, @board) %>

app/views/boards/show.html.haml
%h2 Board#show
= render @pins

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet", :type => "text/css"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pinspiration
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %h1 Pinsparation
      %nav
        %ul
          %li= link_to 'Create new pin', new_pin_path
          %li= link_to 'Create new board', new_board_path
          %li= link_to 'See all pins', pins_path
          %li= link_to 'See all boards', boards_path
    = yield

app/views/pins/_form.html.haml
= form_for @pin do |f|
  - if @pin.errors.any?
    #error_explanation
      %h4
        = pluralize @pin.errors.count, 'error'
        prohibited this pin from being saved
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg
  .pin_form
    = f.label :title
    = f.text_field :title
    = f.label :image_url
    = f.text_field :image_url
    = f.submit

app/views/pins/_pin.html.haml
.pin
  = link_to image_tag(pin.image_url, alt: pin.title), pin
  %ul.options
    %li= link_to 'edit', edit_pin_path(pin)
    %li= link_to 'destroy', pin_path(pin), method: :delete, data: { confirm: 'Are you sure?' }

app/views/pins/edit.html.erb
<h2>Edit Pin</h2>

<%= render 'form' %>

<%= link_to 'Delete Pin', pin_path(@pin), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/pins/edit.html.haml
%h2 Edit Pin?
= render 'form'

app/views/pins/index.html.haml
%h2 Pins#index
= render @pins

app/views/pins/new.html.haml
%h2 New Pin?
= render 'form'

app/views/pins/show.html.haml
%h2 Pins#show
= render @pin

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.erb